### ISSUE TITLE
[Theme] Menu icon is too large, broken

### ISSUE THREAD

**Issue by KleinKravis** [KleinKravis/yaru-mate#1]
### Broken component (Eg; Icons):
Icons

### Description of issue (Eg: Menu icon is too big):
Menu icon is too big, shows Gnome logo instead of Ubuntu MATE roundel

### MATE Layout (Eg: Mutiny):
Traditional

**Comment by hydromalis** [comment]
Just an update with this:
I'm pulling some files down from @ubuntu-mate , they should be committed by tomorrow morning. This is a blocker so we have pulled back from Staging for the time being

**Comment by KleinKravis** [comment]
The package now depends on `ubuntu-mate-artwork` which should fix the issues

**Comment by KleinKravis** [comment]
The package now depends on `ubuntu-mate-artwork` which should fix the issues
